project:
  type: website
  output-dir: docs           # important pour GitHub Pages

website:
  title: "Mon portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos
      - href: viewer3d.qmd     # <-- NOUVEAU : page pour le modèle 3D
        text: Modèle 3D

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
resources:
  - assets/